/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 33.2.0 Wed Apr 28 20:31:30 2021.
 */

#include <string.h>

#include "sc7.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int sc7_airbag_pack(
    uint8_t *dst_p,
    const struct sc7_airbag_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->driver_airbag_fired, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->codriver_airbag_fired, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->driver_seat_occupied, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->codriver_seat_occupied, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->driver_seatbelt_locked, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->codriver_seatbelt_locked, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->airbag_configuration, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->seat_configuration, 0u, 0xffu);

    return (3);
}

int sc7_airbag_unpack(
    struct sc7_airbag_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->driver_airbag_fired |= unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->codriver_airbag_fired |= unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->driver_seat_occupied |= unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->codriver_seat_occupied |= unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->driver_seatbelt_locked |= unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->codriver_seatbelt_locked |= unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->airbag_configuration |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->seat_configuration |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t sc7_airbag_driver_airbag_fired_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_driver_airbag_fired_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_driver_airbag_fired_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_airbag_codriver_airbag_fired_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_codriver_airbag_fired_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_codriver_airbag_fired_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_airbag_driver_seat_occupied_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_driver_seat_occupied_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_driver_seat_occupied_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_airbag_codriver_seat_occupied_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_codriver_seat_occupied_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_codriver_seat_occupied_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_airbag_driver_seatbelt_locked_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_driver_seatbelt_locked_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_driver_seatbelt_locked_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_airbag_codriver_seatbelt_locked_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_codriver_seatbelt_locked_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_codriver_seatbelt_locked_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_airbag_airbag_configuration_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_airbag_configuration_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_airbag_configuration_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_airbag_seat_configuration_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_airbag_seat_configuration_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_airbag_seat_configuration_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc7_abs_pack(
    uint8_t *dst_p,
    const struct sc7_abs_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u8(src_p->abs_info_mux, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u16(src_p->outside_temp, 2u, 0xfcu);
    dst_p[3] |= pack_right_shift_u16(src_p->outside_temp, 6u, 0x3fu);
    dst_p[3] |= pack_left_shift_u32(src_p->speed_km, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u32(src_p->speed_km, 2u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->speed_km, 10u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->speed_km, 18u, 0x3fu);
    dst_p[6] |= pack_left_shift_u8(src_p->handbrake, 6u, 0xc0u);
    dst_p[7] |= pack_right_shift_u8(src_p->handbrake, 2u, 0x3fu);

    switch (src_p->abs_info_mux) {

    case 0:
        dst_p[0] |= pack_left_shift_u8(src_p->info0, 0u, 0xffu);
        dst_p[1] |= pack_left_shift_u8(src_p->info1, 0u, 0xffu);
        break;

    case 1:
        dst_p[0] |= pack_left_shift_u8(src_p->info2, 0u, 0xffu);
        dst_p[1] |= pack_left_shift_u8(src_p->info3, 0u, 0xffu);
        break;

    case 2:
        dst_p[0] |= pack_left_shift_u8(src_p->info4, 0u, 0xffu);
        dst_p[1] |= pack_left_shift_u8(src_p->info5, 0u, 0xffu);
        break;

    case 3:
        dst_p[0] |= pack_left_shift_u8(src_p->info6, 0u, 0xffu);
        dst_p[1] |= pack_left_shift_u8(src_p->info7, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int sc7_abs_unpack(
    struct sc7_abs_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->abs_info_mux |= unpack_right_shift_u8(src_p[2], 0u, 0x03u);
    dst_p->outside_temp |= unpack_right_shift_u16(src_p[2], 2u, 0xfcu);
    dst_p->outside_temp |= unpack_left_shift_u16(src_p[3], 6u, 0x3fu);
    dst_p->speed_km |= unpack_right_shift_u32(src_p[3], 6u, 0xc0u);
    dst_p->speed_km |= unpack_left_shift_u32(src_p[4], 2u, 0xffu);
    dst_p->speed_km |= unpack_left_shift_u32(src_p[5], 10u, 0xffu);
    dst_p->speed_km |= unpack_left_shift_u32(src_p[6], 18u, 0x3fu);
    dst_p->handbrake |= unpack_right_shift_u8(src_p[6], 6u, 0xc0u);
    dst_p->handbrake |= unpack_left_shift_u8(src_p[7], 2u, 0x3fu);

    switch (dst_p->abs_info_mux) {

    case 0:
        dst_p->info0 |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
        dst_p->info1 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 1:
        dst_p->info2 |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
        dst_p->info3 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 2:
        dst_p->info4 |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
        dst_p->info5 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 3:
        dst_p->info6 |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
        dst_p->info7 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

uint8_t sc7_abs_info0_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info0_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_info2_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info2_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_info4_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info4_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_info6_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info6_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_info1_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info1_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_info3_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info3_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_info5_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info5_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_info7_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_info7_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_info7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_abs_abs_info_mux_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_abs_info_mux_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_abs_info_mux_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint16_t sc7_abs_outside_temp_encode(double value)
{
    return (uint16_t)((value - -40.0) / 0.05);
}

double sc7_abs_outside_temp_decode(uint16_t value)
{
    return (((double)value * 0.05) + -40.0);
}

bool sc7_abs_outside_temp_is_in_range(uint16_t value)
{
    return ((value >= 800u) && (value <= 2800u));
}

uint32_t sc7_abs_speed_km_encode(double value)
{
    return (uint32_t)(value / 0.2);
}

double sc7_abs_speed_km_decode(uint32_t value)
{
    return ((double)value * 0.2);
}

bool sc7_abs_speed_km_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint8_t sc7_abs_handbrake_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_abs_handbrake_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_abs_handbrake_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc7_cruise_control_status_pack(
    uint8_t *dst_p,
    const struct sc7_cruise_control_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->cc_enabled, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->cc_activated, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u16(src_p->speed_km, 2u, 0xfcu);
    dst_p[1] |= pack_right_shift_u16(src_p->speed_km, 6u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->speed_km, 14u, 0x03u);

    return (3);
}

int sc7_cruise_control_status_unpack(
    struct sc7_cruise_control_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->cc_enabled |= unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->cc_activated |= unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->speed_km |= unpack_right_shift_u16(src_p[0], 2u, 0xfcu);
    dst_p->speed_km |= unpack_left_shift_u16(src_p[1], 6u, 0xffu);
    dst_p->speed_km |= unpack_left_shift_u16(src_p[2], 14u, 0x03u);

    return (0);
}

uint8_t sc7_cruise_control_status_cc_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_cruise_control_status_cc_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_cruise_control_status_cc_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_cruise_control_status_cc_activated_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_cruise_control_status_cc_activated_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_cruise_control_status_cc_activated_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t sc7_cruise_control_status_speed_km_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_cruise_control_status_speed_km_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_cruise_control_status_speed_km_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc7_emission_pack(
    uint8_t *dst_p,
    const struct sc7_emission_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->mil, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u16(src_p->enginespeed, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u16(src_p->enginespeed, 7u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->enginespeed, 15u, 0x01u);
    dst_p[2] |= pack_left_shift_u16(src_p->nox_sensor, 1u, 0xfeu);
    dst_p[3] |= pack_right_shift_u16(src_p->nox_sensor, 7u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->nox_sensor, 15u, 0x01u);

    return (5);
}

int sc7_emission_unpack(
    struct sc7_emission_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->mil |= unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->enginespeed |= unpack_right_shift_u16(src_p[0], 1u, 0xfeu);
    dst_p->enginespeed |= unpack_left_shift_u16(src_p[1], 7u, 0xffu);
    dst_p->enginespeed |= unpack_left_shift_u16(src_p[2], 15u, 0x01u);
    dst_p->nox_sensor |= unpack_right_shift_u16(src_p[2], 1u, 0xfeu);
    dst_p->nox_sensor |= unpack_left_shift_u16(src_p[3], 7u, 0xffu);
    dst_p->nox_sensor |= unpack_left_shift_u16(src_p[4], 15u, 0x01u);

    return (0);
}

uint8_t sc7_emission_mil_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_emission_mil_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_emission_mil_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t sc7_emission_enginespeed_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_emission_enginespeed_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_emission_enginespeed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_emission_nox_sensor_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_emission_nox_sensor_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_emission_nox_sensor_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc7_steering_info_pack(
    uint8_t *dst_p,
    const struct sc7_steering_info_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->right_hand_drive, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u16(src_p->wheel_angle, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u16(src_p->wheel_angle, 7u, 0x7fu);

    return (2);
}

int sc7_steering_info_unpack(
    struct sc7_steering_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->right_hand_drive |= unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->wheel_angle |= unpack_right_shift_u16(src_p[0], 1u, 0xfeu);
    dst_p->wheel_angle |= unpack_left_shift_u16(src_p[1], 7u, 0x7fu);

    return (0);
}

uint8_t sc7_steering_info_right_hand_drive_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_steering_info_right_hand_drive_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_steering_info_right_hand_drive_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t sc7_steering_info_wheel_angle_encode(double value)
{
    return (uint16_t)((value - -800.0) / 0.1);
}

double sc7_steering_info_wheel_angle_decode(uint16_t value)
{
    return (((double)value * 0.1) + -800.0);
}

bool sc7_steering_info_wheel_angle_is_in_range(uint16_t value)
{
    return (value <= 16383u);
}

int sc7_anti_theft_pack(
    uint8_t *dst_p,
    const struct sc7_anti_theft_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->challenge, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->challenge, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->challenge, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->challenge, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->challenge, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->challenge, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->challenge, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->challenge, 56u, 0xffu);

    return (8);
}

int sc7_anti_theft_unpack(
    struct sc7_anti_theft_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->challenge |= unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->challenge |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->challenge |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->challenge |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->challenge |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->challenge |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->challenge |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->challenge |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);

    return (0);
}

uint64_t sc7_anti_theft_challenge_encode(double value)
{
    return (uint64_t)(value);
}

double sc7_anti_theft_challenge_decode(uint64_t value)
{
    return ((double)value);
}

bool sc7_anti_theft_challenge_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int sc7_gear_pack(
    uint8_t *dst_p,
    const struct sc7_gear_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[1] |= pack_left_shift_u8(src_p->engaged_gear, 4u, 0xf0u);

    return (2);
}

int sc7_gear_unpack(
    struct sc7_gear_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->engaged_gear |= unpack_right_shift_u8(src_p[1], 4u, 0xf0u);

    return (0);
}

uint8_t sc7_gear_engaged_gear_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_gear_engaged_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_gear_engaged_gear_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int sc7_headlights_pack(
    uint8_t *dst_p,
    const struct sc7_headlights_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->drl, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->low, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->high, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->fog, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->turnsignal_l, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->turnsignal_r, 5u, 0x20u);

    return (1);
}

int sc7_headlights_unpack(
    struct sc7_headlights_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->drl |= unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->low |= unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->high |= unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->fog |= unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->turnsignal_l |= unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->turnsignal_r |= unpack_right_shift_u8(src_p[0], 5u, 0x20u);

    return (0);
}

uint8_t sc7_headlights_drl_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_headlights_drl_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_headlights_drl_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_headlights_low_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_headlights_low_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_headlights_low_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_headlights_high_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_headlights_high_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_headlights_high_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_headlights_fog_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_headlights_fog_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_headlights_fog_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_headlights_turnsignal_l_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_headlights_turnsignal_l_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_headlights_turnsignal_l_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_headlights_turnsignal_r_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_headlights_turnsignal_r_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_headlights_turnsignal_r_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int sc7_wiper_pack(
    uint8_t *dst_p,
    const struct sc7_wiper_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->wiper_mode, 0u, 0xffu);

    return (1);
}

int sc7_wiper_unpack(
    struct sc7_wiper_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->wiper_mode |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t sc7_wiper_wiper_mode_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_wiper_wiper_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_wiper_wiper_mode_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc7_bcc_pack(
    uint8_t *dst_p,
    const struct sc7_bcc_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u32(src_p->milage1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->milage1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->milage1, 16u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->milage2, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->milage2, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->milage2, 16u, 0xffu);

    return (6);
}

int sc7_bcc_unpack(
    struct sc7_bcc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->milage1 |= unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->milage1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->milage1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->milage2 |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->milage2 |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->milage2 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);

    return (0);
}

uint32_t sc7_bcc_milage1_encode(double value)
{
    return (uint32_t)(value / 0.1);
}

double sc7_bcc_milage1_decode(uint32_t value)
{
    return ((double)value * 0.1);
}

bool sc7_bcc_milage1_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t sc7_bcc_milage2_encode(double value)
{
    return (uint32_t)(value / 0.1);
}

double sc7_bcc_milage2_decode(uint32_t value)
{
    return ((double)value * 0.1);
}

bool sc7_bcc_milage2_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

int sc7_tank_controller_pack(
    uint8_t *dst_p,
    const struct sc7_tank_controller_t *src_p,
    size_t size)
{
    uint16_t tank_temperature;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u16(src_p->tank_level, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->tank_level, 8u, 0xffu);
    tank_temperature = (uint16_t)src_p->tank_temperature;
    dst_p[2] |= pack_left_shift_u16(tank_temperature, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(tank_temperature, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->filling_status, 0u, 0x0fu);

    return (5);
}

int sc7_tank_controller_unpack(
    struct sc7_tank_controller_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tank_temperature;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->tank_level |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->tank_level |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    tank_temperature = 0u;
    tank_temperature |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    tank_temperature |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->tank_temperature = (int16_t)tank_temperature;
    dst_p->filling_status |= unpack_right_shift_u8(src_p[4], 0u, 0x0fu);

    return (0);
}

uint16_t sc7_tank_controller_tank_level_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_tank_controller_tank_level_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_tank_controller_tank_level_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t sc7_tank_controller_tank_temperature_encode(double value)
{
    return (int16_t)(value);
}

double sc7_tank_controller_tank_temperature_decode(int16_t value)
{
    return ((double)value);
}

bool sc7_tank_controller_tank_temperature_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_tank_controller_filling_status_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_tank_controller_filling_status_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_tank_controller_filling_status_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int sc7_parksensor_front_pack(
    uint8_t *dst_p,
    const struct sc7_parksensor_front_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->sensor1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->sensor1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->sensor2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->sensor2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->sensor3, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->sensor3, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->sensor4, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->sensor4, 8u, 0xffu);

    return (8);
}

int sc7_parksensor_front_unpack(
    struct sc7_parksensor_front_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->sensor1 |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->sensor1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->sensor2 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->sensor2 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->sensor3 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->sensor3 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->sensor4 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->sensor4 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t sc7_parksensor_front_sensor1_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_front_sensor1_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_front_sensor1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_parksensor_front_sensor2_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_front_sensor2_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_front_sensor2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_parksensor_front_sensor3_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_front_sensor3_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_front_sensor3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_parksensor_front_sensor4_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_front_sensor4_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_front_sensor4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc7_parksensor_back_pack(
    uint8_t *dst_p,
    const struct sc7_parksensor_back_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->sensor5, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->sensor5, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->sensor6, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->sensor6, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->sensor7, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->sensor7, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->sensor8, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->sensor8, 8u, 0xffu);

    return (8);
}

int sc7_parksensor_back_unpack(
    struct sc7_parksensor_back_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->sensor5 |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->sensor5 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->sensor6 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->sensor6 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->sensor7 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->sensor7 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->sensor8 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->sensor8 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t sc7_parksensor_back_sensor5_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_back_sensor5_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_back_sensor5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_parksensor_back_sensor6_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_back_sensor6_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_back_sensor6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_parksensor_back_sensor7_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_back_sensor7_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_back_sensor7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_parksensor_back_sensor8_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_parksensor_back_sensor8_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_parksensor_back_sensor8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc7_temperature_pack(
    uint8_t *dst_p,
    const struct sc7_temperature_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u16(src_p->inside_temp_c, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->inside_temp_c, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->outside_temp_c, 4u, 0xf0u);
    dst_p[2] |= pack_right_shift_u16(src_p->outside_temp_c, 4u, 0xffu);

    return (3);
}

int sc7_temperature_unpack(
    struct sc7_temperature_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->inside_temp_c |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->inside_temp_c |= unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->outside_temp_c |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->outside_temp_c |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);

    return (0);
}

uint16_t sc7_temperature_inside_temp_c_encode(double value)
{
    return (uint16_t)((value - -70.0) / 0.05);
}

double sc7_temperature_inside_temp_c_decode(uint16_t value)
{
    return (((double)value * 0.05) + -70.0);
}

bool sc7_temperature_inside_temp_c_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t sc7_temperature_outside_temp_c_encode(double value)
{
    return (uint16_t)((value - -70.0) / 0.05);
}

double sc7_temperature_outside_temp_c_decode(uint16_t value)
{
    return (((double)value * 0.05) + -70.0);
}

bool sc7_temperature_outside_temp_c_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int sc7_air_condition_pack(
    uint8_t *dst_p,
    const struct sc7_air_condition_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->air_condition_on_off, 0u, 0x01u);

    return (1);
}

int sc7_air_condition_unpack(
    struct sc7_air_condition_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->air_condition_on_off |= unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

uint8_t sc7_air_condition_air_condition_on_off_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_air_condition_air_condition_on_off_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_air_condition_air_condition_on_off_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int sc7_front_left_door_pack(
    uint8_t *dst_p,
    const struct sc7_front_left_door_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int sc7_front_left_door_unpack(
    struct sc7_front_left_door_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)src_p;
    (void)size;

    memset(dst_p, 0, sizeof(*dst_p));

    return (0);
}

int sc7_front_right_door_pack(
    uint8_t *dst_p,
    const struct sc7_front_right_door_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int sc7_front_right_door_unpack(
    struct sc7_front_right_door_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)src_p;
    (void)size;

    memset(dst_p, 0, sizeof(*dst_p));

    return (0);
}

int sc7_back_left_door_pack(
    uint8_t *dst_p,
    const struct sc7_back_left_door_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int sc7_back_left_door_unpack(
    struct sc7_back_left_door_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)src_p;
    (void)size;

    memset(dst_p, 0, sizeof(*dst_p));

    return (0);
}

int sc7_back_right_door_pack(
    uint8_t *dst_p,
    const struct sc7_back_right_door_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int sc7_back_right_door_unpack(
    struct sc7_back_right_door_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)src_p;
    (void)size;

    memset(dst_p, 0, sizeof(*dst_p));

    return (0);
}

int sc7_trunk_lid_pack(
    uint8_t *dst_p,
    const struct sc7_trunk_lid_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int sc7_trunk_lid_unpack(
    struct sc7_trunk_lid_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)src_p;
    (void)size;

    memset(dst_p, 0, sizeof(*dst_p));

    return (0);
}

int sc7_driver_seat_pack(
    uint8_t *dst_p,
    const struct sc7_driver_seat_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->headrest, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->backrest, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->seat_pos, 0u, 0xffu);

    return (3);
}

int sc7_driver_seat_unpack(
    struct sc7_driver_seat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->headrest |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->backrest |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->seat_pos |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t sc7_driver_seat_headrest_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_driver_seat_headrest_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_driver_seat_headrest_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_driver_seat_backrest_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_driver_seat_backrest_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_driver_seat_backrest_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_driver_seat_seat_pos_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_driver_seat_seat_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_driver_seat_seat_pos_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc7_codriver_seat_pack(
    uint8_t *dst_p,
    const struct sc7_codriver_seat_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->headrest, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->backrest, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->seat_pos, 0u, 0xffu);

    return (3);
}

int sc7_codriver_seat_unpack(
    struct sc7_codriver_seat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->headrest |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->backrest |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->seat_pos |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t sc7_codriver_seat_headrest_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_codriver_seat_headrest_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_codriver_seat_headrest_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_codriver_seat_backrest_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_codriver_seat_backrest_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_codriver_seat_backrest_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_codriver_seat_seat_pos_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_codriver_seat_seat_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_codriver_seat_seat_pos_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc7_radio_pack(
    uint8_t *dst_p,
    const struct sc7_radio_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->station_mux, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->signal_strength, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->signal_strength, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->is_enabled, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->traffic_info, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->mute, 2u, 0x04u);

    switch (src_p->station_mux) {

    case 0:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id1, 0u, 0xffu);
        break;

    case 1:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id2, 0u, 0xffu);
        break;

    case 2:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id3, 0u, 0xffu);
        break;

    case 3:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id4, 0u, 0xffu);
        break;

    case 4:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id5, 0u, 0xffu);
        break;

    case 5:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id6, 0u, 0xffu);
        break;

    case 6:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id7, 0u, 0xffu);
        break;

    case 7:
        dst_p[1] |= pack_left_shift_u8(src_p->station_id7, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (5);
}

int sc7_radio_unpack(
    struct sc7_radio_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->station_mux |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->signal_strength |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->signal_strength |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->is_enabled |= unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->traffic_info |= unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->mute |= unpack_right_shift_u8(src_p[4], 2u, 0x04u);

    switch (dst_p->station_mux) {

    case 0:
        dst_p->station_id1 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 1:
        dst_p->station_id2 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 2:
        dst_p->station_id3 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 3:
        dst_p->station_id4 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 4:
        dst_p->station_id5 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 5:
        dst_p->station_id6 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 6:
        dst_p->station_id7 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    case 7:
        dst_p->station_id7 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

uint8_t sc7_radio_station_mux_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_mux_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_mux_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id1_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id1_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id2_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id2_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id3_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id3_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id4_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id4_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id5_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id5_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id6_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id6_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id7_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id7_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_station_id7_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_station_id7_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_station_id7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t sc7_radio_signal_strength_encode(double value)
{
    return (uint16_t)(value);
}

double sc7_radio_signal_strength_decode(uint16_t value)
{
    return ((double)value);
}

bool sc7_radio_signal_strength_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_radio_is_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_is_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_is_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_radio_traffic_info_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_traffic_info_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_traffic_info_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_radio_mute_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_radio_mute_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_radio_mute_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int sc7_navigation_pack(
    uint8_t *dst_p,
    const struct sc7_navigation_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->is_enabled, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->announcements, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->guidance, 2u, 0xfcu);
    dst_p[1] |= pack_right_shift_u8(src_p->guidance, 6u, 0x03u);

    return (2);
}

int sc7_navigation_unpack(
    struct sc7_navigation_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->is_enabled |= unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->announcements |= unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->guidance |= unpack_right_shift_u8(src_p[0], 2u, 0xfcu);
    dst_p->guidance |= unpack_left_shift_u8(src_p[1], 6u, 0x03u);

    return (0);
}

uint8_t sc7_navigation_is_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_navigation_is_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_navigation_is_enabled_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_navigation_announcements_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_navigation_announcements_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_navigation_announcements_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t sc7_navigation_guidance_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_navigation_guidance_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_navigation_guidance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc7_date_time_pack(
    uint8_t *dst_p,
    const struct sc7_date_time_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->day, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->month, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->year, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->weekday, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->hour, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->minute, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->second, 0u, 0xffu);

    return (7);
}

int sc7_date_time_unpack(
    struct sc7_date_time_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->day |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->month |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->year |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->weekday |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->hour |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->minute |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->second |= unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t sc7_date_time_day_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_date_time_day_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_date_time_day_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 31u));
}

uint8_t sc7_date_time_month_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_date_time_month_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_date_time_month_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 12u));
}

uint8_t sc7_date_time_year_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_date_time_year_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_date_time_year_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t sc7_date_time_weekday_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_date_time_weekday_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_date_time_weekday_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc7_date_time_hour_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_date_time_hour_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_date_time_hour_is_in_range(uint8_t value)
{
    return (value <= 23u);
}

uint8_t sc7_date_time_minute_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_date_time_minute_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_date_time_minute_is_in_range(uint8_t value)
{
    return (value <= 59u);
}

uint8_t sc7_date_time_second_encode(double value)
{
    return (uint8_t)(value);
}

double sc7_date_time_second_decode(uint8_t value)
{
    return ((double)value);
}

bool sc7_date_time_second_is_in_range(uint8_t value)
{
    return (value <= 59u);
}
